### ISSUE TITLE
Pb de compréhension

### ISSUE THREAD

**Issue by ClemWasChoosen** [UPHF/algo4#3]
Bonjour, 
Dans cette fonction, je ne comprends pas où est-ce qu'on incrémente les deux valeurs nombreG et nombreD. Pouvez-vous m'éclairer?

Merci !

https://github.com/UPHF/algo4/blob/aad8bf97a6a74b83bc207249dfa311981585070e/example_abr/main.c#L130

**Comment by martinezmatias** [comment]
Bonjour 
> nombreG et nombreD

IIs correspondent aux nombre de nodes à gauche et à droit.

**Comment by ClemWasChoosen** [comment]
Oui mais je veux dire, où est ce qu’ils prennent +1? Puisqu’on fait que appel à la fonction, on n’écrit pas nombreD+1 ou nombreG+1

**Comment by martinezmatias** [comment]
ici: 
https://github.com/UPHF/algo4/blob/aad8bf97a6a74b83bc207249dfa311981585070e/example_abr/main.c#L140

**Comment by ClemWasChoosen** [comment]
Ok parfait, merci
